### ISSUE TITLE
errorLines causes page to go blank

### ISSUE THREAD

**Issue by pixelass** [sinnerschrader/esdoc-custom-theme#3]
## Issue description
When clicking on a link in "sources.html" that has coverage data the resulting hash in the url causes an issue

## Steps to reproduce
Open a page with `index.js.html#errorLines=1,19,404` at the end

Example: `file:///Users/greada/Documents/workspace/private/gaffney/docs/api/file/@gaffney/rise-set/src/index.js.html#errorLines=1,19,404`

## Log

```
bundle.js:formatted:82 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#errorLines=1,19,404' is not a valid selector.
    at t.$ (file:///Users/greada/Documents/workspace/private/gaffney/docs/api/script/bundle.js:1:1420)
    at a (file:///Users/greada/Documents/workspace/private/gaffney/docs/api/script/bundle.js:1:219771)
    at Object.<anonymous> (file:///Users/greada/Documents/workspace/private/gaffney/docs/api/script/bundle.js:1:219813)
    at r (file:///Users/greada/Documents/workspace/private/gaffney/docs/api/script/bundle.js:1:385)
    at Object.<anonymous> (file:///Users/greada/Documents/workspace/private/gaffney/docs/api/script/bundle.js:1:219076)
    at r (file:///Users/greada/Documents/workspace/private/gaffney/docs/api/script/bundle.js:1:385)
    at file:///Users/greada/Documents/workspace/private/gaffney/docs/api/script/bundle.js:1:733
    at file:///Users/greada/Documents/workspace/private/gaffney/docs/api/script/bundle.js:1:743
    at file:///Users/greada/Documents/workspace/private/gaffney/docs/api/script/bundle.js:1:158
    at file:///Users/greada/Documents/workspace/private/gaffney/docs/api/script/bundle.js:1:223
t.$ @ bundle.js:formatted:82
a @ bundle.js:formatted:9825
(anonymous) @ bundle.js:formatted:9829
r @ bundle.js:formatted:22
(anonymous) @ bundle.js:formatted:9764
r @ bundle.js:formatted:22
(anonymous) @ bundle.js:formatted:53
(anonymous) @ bundle.js:formatted:54
(anonymous) @ bundle.js:formatted:7
(anonymous) @ bundle.js:formatted:11
```

## Versions

esdoc-custom-theme: 1.0.1

**Comment by pixelass** [comment]
fixed by 5042eb4e393ae4a9aa04647fb636d5c9c4e8d706
